FROM alpine
RUN apk add --update ca-certificates && \
    rm -rf /var/cache/apk/* /tmp/*

ENV CORS_ALLOWED_HEADERS "Content-Type,Accept,Authorization"
ENV CORS_ALLOWED_ORIGINS "*"
ENV CORS_ALLOWED_METHODS "GET,POST"

WORKDIR /
COPY micro ./
ENTRYPOINT ["./micro"]
CMD ["api","--namespace=dongfeng.svc.core.proxy","--handler=http","--address=0.0.0.0:8080"]