FROM golang:1.12-alpine as builder

RUN apk update && apk add --no-cache --update ca-certificates

FROM scratch

ENV CORS_ALLOWED_HEADERS "Content-Type,Accept,Authorization"
ENV CORS_ALLOWED_ORIGINS "*"
ENV CORS_ALLOWED_METHODS "GET,POST"

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY micro ./
ENTRYPOINT ["./micro"]
CMD ["api","--namespace=dongfeng.svc.core.proxy","--handler=http","--address=0.0.0.0:8080"]